name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: start
      run: echo start
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Electron Builder Action
      working-directory: docs
      uses: samuelmeuli/action-electron-builder@v1.0.0
    - name: end
      run: echo end
